steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
      - '--set-env-vars'
      - 'MONGO_DB=$_MONGO_DB'
      - '--set-env-vars'
      - 'MAX_SYSTEMS=$_MAX_SYSTEMS'
      - '--set-env-vars'
      - 'SECRET_NAME=projects/$PROJECT_ID/secrets/$_SECRET_NAME/versions/latest'
      - '--set-env-vars'
      - 'BASE_URL=$_BASE_URL'
    id: Deploy
    entrypoint: gcloud
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: mmo-server-stage
  _DEPLOY_REGION: asia-south1
  _LABELS: gcb-trigger-id=e2103a41-e827-49bb-9f80-cc15488b40ce
  _TRIGGER_ID: e2103a41-e827-49bb-9f80-cc15488b40ce
  _GCR_HOSTNAME: asia.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - mmo-server-stage
